twitter-to-kafka-service:
  twitter-keyWords:
    - Microservices


  message:
    Welcome Home
  enable-v2-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: AAAAAAAAAAAAAAAAAAAAALVlcwEAAAAAGYkPSqllte0yNJ1u9bjTUJnZvKQ%3DrEyerXf4HiDCBPwKADNAL8637Prn87is9VS6IPG3lnsZEmXKEL