
spring:
  application:
    name: twitter-to-kafka-service
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: twitter_to_kafka
  security:
    user:
      name: eventDrivenZack
      password: eventDrivenZack

management:
  endpoints:
    web:
      exposure:
        include: refresh

  endpoint:
    refresh:
      enabled: true







