spring:
  application:
    name: kafka-to-elastic-service
  config:
    import: 'configserver:'
    username: spring_cloud_user
    password: ENC (kIg5mA002MZ0ipLLAS0OKEYR/wMo8iUHcYSTnUt7zGTzl7vn8/lJjYZqx8fmMlD+/Jajqktrt+/IHerk9BRcQw==)
    fail-fast: true

  profiles:
    active: kafka-to-elastic-service

  security:
    user:
      name: spring_cloud_user
      password: ENC (kIg5mA002MZ0ipLLAS0OKEYR/wMo8iUHcYSTnUt7zGTzl7vn8/lJjYZqx8fmMlD+/Jajqktrt+/IHerk9BRcQw==)


  cloud:
    config:
      allow-override: true
      override-none: true
